---
sidebar: sidebar 
permalink: xcp/xcp-bp-smb-cifs-csv.html 
keywords: csv, data dump 
summary: O comando nesta seção despeja dados no formato CSV.  Você pode somar a coluna de tamanho para obter o tamanho total dos dados. 
---
= Criando um arquivo CSV a partir do compartilhamento SMB/CIFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O comando a seguir despeja dados no formato CSV.  Você pode somar a coluna de tamanho para obter o tamanho total dos dados.

....
xcp scan -match "((now-x.atime) / 3600) > 31*day" -fmt "'{}, {}, {}, {}'.format(relpath, name, strftime(x.atime, '%y-%m-%d-%H:%M:%S'), humanize_size(size))" -preserve-atime  >file.csv
....
A saída deve ser semelhante a este exemplo:

....
erase\report_av_fp_cdot_crosstab.csvreport_av_fp_cdot_crosstab.csv20-01-29-10:26:2449.6MiB
....
Para escanear até a profundidade de três subdiretórios e fornecer o resultado em ordem de classificação, execute o `xcp -du` comando e despeja o tamanho em cada nível de diretório até a profundidade de três subdiretórios.

....
./xcp  scan -du -depth 3 NFS_Server_IP:/source_vol
 
....
Para classificar, despeje as informações em um arquivo CSV e classifique-as.

....
xcp scan -match "type == d" -depth 3 -fmt "'{}, {}, {}, {}'.format(name, relpath, size)" NFS_Server_IP:/share > directory_report.csv
....
Este é um relatório personalizado que usa o `-fmt` comando.  Ele verifica todos os diretórios e despeja o nome do diretório, o caminho e o tamanho do diretório em um arquivo CSV.  Você pode classificar a coluna de tamanho no aplicativo de planilha.
