---
sidebar: sidebar 
permalink: xcp/xcp-bp-hpc.html 
keywords: use case, gpfs, nfs 
summary: Usamos o NetApp XCP para migrar os dados do GPFS para o NFS para que as GPUs possam processar os dados.  A IA normalmente processa dados de um sistema de arquivos de rede. 
---
= Computação de alto desempenho para ONTAP NFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Este caso de uso é baseado em solicitações de organizações de campo.  Alguns clientes da NetApp têm seus dados em um ambiente de computação de alto desempenho, que fornece análise de dados para modelos de treinamento e permite que organizações de pesquisa obtenham insights e compreensão de grandes quantidades de dados digitais.  Os engenheiros de campo da NetApp precisam de um procedimento detalhado para extrair os dados do GPFS da IBM para o NFS.  Usamos o NetApp XCP para migrar os dados do GPFS para o NFS para que as GPUs possam processar os dados.  A IA normalmente processa dados de um sistema de arquivos de rede.

Para obter mais informações sobre o caso de uso de computação de alto desempenho para ONTAP NFS, uma demonstração gravada e resultados de testes, consulte o https://blog.netapp.com/data-migration-xcp["Usando XCP para mover dados de um data lake e computação de alto desempenho para o ONTAP NFS"^] blog.

Para obter etapas detalhadas sobre como mover dados do MapR-FS para o ONTAP NFS usando o NetApp XCP, consulte o Apêndice A: GPFS para NFS - Etapas detalhadaslink:https://docs.netapp.com/us-en/netapp-solutions-ai/data-analytics/bda-ai-introduction.html["aqui"^] .
