---
sidebar: sidebar 
permalink: protection-security-resources.html 
keywords: 'netapp, solutions, data management, what"s new, updates, change log' 
summary: Relatórios técnicos adicionais relacionados à proteção e segurança de dados. 
---
= Recursos adicionais para proteção e segurança de dados
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Confira os links abaixo para acessar relatórios técnicos relacionados à proteção e segurança de dados.



== NVA-1143: NetApp HCI - Controles de segurança NIST para FISMA com HyTrust para infraestrutura multilocatária - Projeto e implantação NVA

Arvind Ramakrishnan, Abhinav Singh, NetApp

O NVA-1143 descreve como o NetApp HCI pode ser projetado e implantado para atender aos controles de segurança e privacidade do National Institute of Standards and Technology (NIST) SP 800-53 Revisão 4, que são cruciais para infraestruturas de nuvem privada e implantações multilocatárias.

link:https://www.netapp.com/pdf.html?item=/media/17065-nva1143pdf.pdf["NVA-1143: NetApp HCI - Controles de segurança NIST para FISMA com HyTrust para infraestrutura multilocatária - Projeto e implantação NVA"^]



== TR-4320: NetApp E-Series e Commvault Data Platform V11 - Arquitetura de referência e práticas recomendadas de armazenamento

Akash Gupta, NetApp Girish Chanchlani, Commvault

O TR-4320 descreve a arquitetura de referência e as práticas recomendadas ao usar o armazenamento NetApp E-Series em um ambiente Commvault Data Platform V11.  A Commvault e a NetApp desenvolveram em conjunto esta arquitetura de referência para fornecer orientação para implantações da Commvault Data Platform V11 com armazenamento NetApp E-Series, o que acelerará o tempo de aplicação desta solução.

link:https://www.netapp.com/pdf.html?item=/media/17042-tr4320pdf.pdf["TR-4320: NetApp E-Series e Commvault Data Platform V11 - arquitetura de referência e práticas recomendadas de armazenamento"^]



== TR-4471: Arquitetura de referência das séries E e EF e práticas recomendadas de armazenamento com Veeam Backup & Replication 9.5

Akash Gupta, NetApp Shawn Lieu (Américas), Stefan Renner (EMEA) e Michael Cade (Desempenho), Veeam

O TR-4471 descreve a arquitetura de referência e as práticas recomendadas ao usar o armazenamento NetApp E-Series em um ambiente Veeam Backup & Replication 9.5.

link:https://www.netapp.com/pdf.html?item=/media/17159-tr4471pdf.pdf["TR-4471: Arquitetura de referência das séries E e EF e práticas recomendadas de armazenamento com Veeam Backup  Replication 9.5"^]



== TR-4704: Implantando o Veritas NetBackup com armazenamento NetApp E-Series

Akash Gupta e Principled Technologies, NetApp

TR-4704 descreve a implantação do Veritas NetBackup no armazenamento NetApp E-Series.

link:https://www.netapp.com/pdf.html?item=/media/16433-tr-4704pdf.pdf["TR-4704: Implantando o Veritas NetBackup com armazenamento NetApp E-Series"^]
